#+STARTUP: overview
#+TITLE: Emacs Config - Linux
#+CREATOR: Inspired by Dawid 'daedreth' Eckert and other much more talented people
#+LANGUAGE: en
#+OPTIONS: num:nil
#+ATTR_HTML: :style margin-left: auto; margin-right: auto;
* Major conveniences
These utilities create a nice environment
** Visiting the configuration
Quickly edit =~/.emacs.d/config.org=
#+BEGIN_SRC emacs-lisp
(defun ak/config-visit ()
  (interactive)
  (find-file "~/.emacs.d/config.org"))
;;(global-set-key (kbd "C-c e") 'config-visit)
(define-key ak-map "0" 'ak/config-visit)
#+END_SRC

** Reloading the configuration
You can also manually invoke =config-reload=.
#+BEGIN_SRC emacs-lisp
(defun ak/config-reload ()
  "Reloads ~/.emacs.d/config.org at runtime"
  (interactive)
  (org-babel-load-file (expand-file-name "~/.emacs.d/config.org")))
;;(global-set-key (kbd "C-c r") 'config-reload)
(define-key ak-map "r" 'ak/config-reload)
#+END_SRC

* Instant messaging
I like IRC, I also like other protocols but I enjoy IRC most, it's obvious that I long
for a way to do my messaging from within emacs.
There is plenty of IRC clients in the repositories, and some more in the emacs repositories
but I find that the default =erc= does the job best, it's easy to use and offers some conveniences
that more sophisticated ones don't, so I use it.

** erc, also known as "a way to ask for help on #emacs"
You might want to edit the default nick, it's password protected anyway so don't bother.

*** Some common settings
This also hides some of the channel messages to avoid cluttering the buffer.
The other line changes the prompt for each channel buffer to match the channel name,
this way you always know who you are typing to.
#+BEGIN_SRC emacs-lisp
 (setq erc-nick "fatman03"
       erc-prompt (lambda () (concat "[" (buffer-name) "]"))
       erc-hide-list '("JOIN" "PART" "QUIT"))
#+END_SRC

*** Poor mans selectable server list
What it says on the tin, this changes the =erc= history to include the server I connect to often.
#+BEGIN_SRC emacs-lisp
(setq erc-server-history-list '("irc.libera.chat"
                                "localhost"))
#+END_SRC

*** Nick highlighting
You can even highlight nicks to make the buffers a bit more visually pleasing and easier to look at.
#+BEGIN_SRC emacs-lisp
(use-package erc-hl-nicks
 :straight t
 :config
   (erc-update-modules))
#+END_SRC

* Mail
** mu4e
#+begin_src emacs-lisp
(use-package mu4e
  :straight nil
  :defer 20
  :config

  (setq user-mail-address "akkartha@gmail.com"
        user-full-name  "Arun Kartha"
        mu4e-compose-signature (concat "Arun Kartha\n"
                                       "mailto:akkartha@gmail.com")
        mu4e-compose-format-flowed t)

  (setq mu4e-change-filenames-when-moving t)

  (setq mu4e-update-interval (* 10 60))
  (setq mu4e-get-mail-command "mbsync -a")
  (setq mu4e-maildir "~/Mail")

  (setq mu4e-drafts-folder "/Gmail/[Gmail]/Drafts")
  (setq mu4e-sent-folder "/Gmail/[Gmail]/Sent Mail")
  (setq mu4e-refile-folder "/Gmail/[Gmail]/All Mail")
  (setq mu4e-trash-folder "/Gmail/[Gmail]/Trash")

  (setq mu4e-maildir-shortcuts
        '(("/Inbox"                . ?i)
          ("/Gmail/[Gmail]/Sent Mail"    . ?s)
          ("/Gmail/[Gmail]/Trash"        . ?t)
          ("/Gmail/[Gmail]/Drafts"       . ?d)
          ("/Gmail/[Gmail]/All Mail"     . ?a))))
#+end_src
** SMTP
#+begin_src emacs-lisp
(setq smtpmail-smtp-server "smtp.gmail.com"
      smtpmail-smtp-service 465
      smtpmail-stream-type 'ssl)
#+end_src


